stactof/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='details'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

]

stactof/stactof/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls'), name="polls"),
    path('admin/', admin.site.urls),
]

stactof/polls/models.py
from django.db import models
from django.db.models.functions import datetime
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

stactof/polls/views.py
# from django.db.migrations import loader
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse

from .models import Choice, Question


#
#
# def index(request):
#     questions = Question.objects.all()
#     # res = ""
#     # for q in questions:
#     #     res += str(q.id) + ". " + q.question + "<br>"
#     print(questions)
#     return render(request, "polls/index.html", {'question': questions})
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     output = ', '.join([q.question_text for q in latest_question_list])
#     return HttpResponse(output)
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('polls/index.html')
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return HttpResponse(template.render(context, request))
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


#
# def detail(request, question_id):
#     questions = get_object_or_404(Question, pk=question_id)
#     # rez = "<H3>" + question.question + "<H3>: <br>"
#     # for answer in question.choice_set.all():
#     #     rez += answer.choice_text + " vote: " + str(answer.votes) + "<br>"
#     return render(request, "polls/details.html", {'questions': questions})
def detail(request, question_id):
    # question = Question.objects.get(pk=question_id)
    choice_list = Choice.objects.filter(question_id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    prev = question_id - 1
    nexts = question_id + 1
    last_question_id = len(Question.objects.filter())
    if question_id != last_question_id:
        next_question = Question.objects.filter(id=nexts)
        for i in next_question:
            next_questions = i
    else:
        next_questions = 0

    if question_id > 1:
        prev_question = Question.objects.filter(id=prev)
        for i in prev_question:
            prev_questions = i
    else:
        prev_questions = 0


    return render(request, 'polls/details.html',
                  {'question': question, 'choice': choice_list,
                   'prev': prev, 'next': nexts, 'last': last_question_id,
                   'prev_q': prev_questions, 'next_q': next_questions})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.POST.get('choice'):
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:details', args=(question.id,)))

    elif request.POST.get('minus'):
        selected_choice = question.choice_set.get(pk=request.POST['minus'])
        selected_choice.votes -= 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:details', args=(question.id,)))

stactof/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%block title%} {%endblock%}</title>
</head>
<body bgcolor="silver">
{%block main%}
{%endblock%}
</body>
</html>

stactof/polls/templates/polls/details.html
{%extends "polls/base.html" %}

{%block title%}Questions{%endblock%}

{%block main%}
<!--{% if choice %}-->
<!--    <ul>-->
<!--    {% for q in choice %}-->
<!--        <li>{{ q.choice_text }}</li>-->
<!--    {% endfor %}-->
<!--    </ul>-->
<!--{% else %}-->
<!--    <p>No choice are available.</p>-->
<!--{% endif %}-->
<center>
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<!--<form action="{% url 'polls:vote' question.id %}" method="post">-->
<!--{% csrf_token %}-->
<!--{% for choice in question.choice_set.all %}-->
<!--    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">-->
<!--    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }} [ {{ choice.votes }} ] votes  <input type="submit" value="Vote"></label><br>-->

<!--    {% endfor %}-->

<!--    </form>-->
<!-- -&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;<br>-->
<!--<form action="{% url 'polls:vote' question.id %}" method="post">-->
<!--{% csrf_token %}-->
<!--{% for choice in question.choice_set.all %}-->
<!--    <label>{{ choice.choice_text }}   <input type="submit" name="choice" id="choice{{ forloop.counter }}" value="👍{{ choice.votes }}  {{ choice.id }}"></label><br>-->
<!--    {% endfor %}-->
<!--</form>-->


<form  action = "{% url 'polls:vote' question.id %}" method = "post">
    {% csrf_token %}
{% for choice in question.choice_set.all %}
    {{ choice.choice_text }}
    <button type="submit" name="choice"  value="{{ choice.id }}" >+1👍</button>

        <button type="submit" name="minus" value="{{ choice.id }}" >-1👎</button>
 ({{ choice.votes }})<br>
    {% endfor %}
</form>

{%if question.id == 1%}

<a href="/polls/{{next}}">{{next_q}}</a>
{%elif question.id == last%}
    <a href="/polls/{{prev}}">{{prev_q}}</a>
{%else%}
<a href="/polls/{{prev}}">{{prev_q}}</a>
<a href="/polls/{{next}}">{{next_q}}</a>

{%endif%}
</center>
{%endblock%}

stactof/polls/templates/polls/index.html
{%extends "polls/base.html" %}

{%block title%}Questions{%endblock%}

{%block main%}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{%endblock%}

stactof/polls/templates/polls/results.html
{%extends "polls/base.html"%}

{%block title%}<h1>{{ question.question_text }}</h1>{%endblock%}
{%block main%}
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:details' question.id %}">Vote again?</a>
{%endblock%}